Passed Exam
Simple2B/Avantika pull request #7
Opened 2020-07-21 16:55 UTC by LikaDevelop

2020-07-22 08:58 UTC, kipod requested changes
сори, я отказываюсь дальше проверять
этот код точно не работоспособный

2020-07-22 08:58 UTC, kipod commented on app/exam/views.py
> +        exam.save()
flash(f"Exam {exam.name} deleted", "success")

2020-07-22 08:58 UTC, kipod commented on app/exam/views.py
> +    exam_id = int(exam_id)
Please add logging

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    lang = the_lang.lang
please check for None value

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    passed = the_passed.passed
need first at all check for None value **the_passed**

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    the_passed = Result.query.filter(Exam.id == exam_id, User.id == user_id).first()
Wrong code!!! 
```python
Result.query.filter(Result.exam_id == exam_id, Result.user_id == user_id).first()
```

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +        pass
???

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    return redirect(url_for(f"exam.exam_{lang.name}"))
!!! wrong behavior!!!

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +"""Function witch connect with button 'Go', and do field 'passed', true or false"""
??? is it doc string??? That wrong place for it!!!

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +        pass
??? what is it???

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    # Переводим полученные значения в инт
pls add doc-string

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    the_passed = Result.query.filter(Exam.id == exam_id, User.id == user_id).first()
BAD CODE!!!

2020-07-22 08:58 UTC, kipod commented on app/result/controller.py
> +    passed = the_passed.passed
COPY PASTE of BAD CODE!!!!!

2020-07-22 08:58 UTC, kipod commented on app/result/models.py
> +""" Model of result exam must have this field: id, passed (true/false), exam_id, user_id"""
WRONG PLACE for the doc-string!

2020-07-22 08:58 UTC, kipod commented on app/result/models.py
> +id = db.Column(db.Integer, primary_key=True)
!!!! BAD INTENTION!!!

2020-07-22 11:28 UTC, kipod requested changes

2020-07-22 11:28 UTC, kipod commented on app/exam/views.py
> +    exam_id = int(exam_id)
Лика, добавь тут логи, не игнорируй мои замечания, плиз

2020-07-22 11:28 UTC, kipod commented on app/exam/views.py
>  exam_blueprint = Blueprint("exam", __name__)
добавь логи в эту функцию

2020-07-22 11:28 UTC, kipod commented on app/result/controller.py
> +
это лишняя строчка, убери ее пожалуйста

2020-07-22 11:28 UTC, kipod commented on app/result/controller.py
> +        # Создать новый инстанс БД
ты имела ввиду: создание новой базы данных? :)

2020-07-22 11:28 UTC, kipod commented on app/result/controller.py
> +    passed = the_passed.passed
странный код... 
ты только что установила поле в True и сразу следующей строчкой получаешь его значение и дальше делаешь какую то проверку???

2020-07-22 11:28 UTC, kipod commented on app/result/controller.py
> +        passed = True
очень странный код - который ни на что не влияет!!!
почисть пожалуйста

2020-07-22 11:28 UTC, kipod commented on app/result/controller.py
> +    the_passed.passed = True
установила значение, но не сохранила!
надо вызвать save()

2020-07-22 11:28 UTC, kipod commented on app/result/controller.py
> +    the_passed.passed = False
установила значение но не сохранила!

2020-07-22 11:28 UTC, kipod commented on app/result/models.py
> +""" Model of results exam must have this field: id, passed (true/false), exam_id, user_id"""
wrong place for doc string

2020-07-22 11:28 UTC, kipod commented on app/result/models.py
> +
удаляй эти строчки

2020-07-22 11:28 UTC, kipod commented on app/result/views.py
> +    exam = Exam.query.all()
exams

2020-07-22 11:28 UTC, kipod commented on app/result/views.py
> +    user = current_user.username
user --> user_name

2020-07-22 11:28 UTC, kipod commented on app/templates/auth/register.html
> +</style>
у меня несколько вопросов к этому коду:

1. зачем он нужен?
2. если он нужен - то давай добавим comments
3. почему он не в base.html, лучше в .css file?

2020-07-22 11:28 UTC, kipod commented on app/templates/auth/user_edit.html
> +</style>
same questions

2020-07-22 11:28 UTC, kipod commented on app/templates/exam/status.html
> +        </tr>
Как я понимаю, это должно быть внутри цикла for.
Так как оно сейчас написано, работать не должно, потому что в exam лежит list of exam

2020-07-22 11:28 UTC, kipod commented on app/result/views.py
> +    return render_template("exam/status.html", tabs=tabs, user=user, exam=exam)
да - так и есть... ты назвала переменную exam, а на самом деле хранишь в ней список экзаменов, и как результат ты запуталась и не правильно написала template

2020-07-22 11:28 UTC, kipod commented on tests/test_exam_result.py
> +    go_pass_exam(exam_id=1, user_id=1)
тут необходимо добавить проверки:
получи Result для этого студента и этого экзамена, и проверь поле passed

2020-07-22 11:28 UTC, kipod commented on tests/test_exam_result.py
> +    next_to_pass_exam(exam_id=1, user_id=1)
тоже самое - добавь проверки

2020-07-22 11:28 UTC, kipod commented on tests/test_exam_result.py
> +    # user = User.query.all()[0]
почему ты закоментировала этот код - ведь где гарантия что в базе всегда есть экзамен с id=1 и пользователь с id=1

2020-07-22 11:28 UTC, kipod commented on tests/test_exam_result.py
> +    # user = User.query.all()[0]
хотя... базу же мы сами генерим... ок - оставь так. Но значения 1 целесообразно поместить в именованные константы

2020-07-22 12:19 UTC, LikaDevelop commented on app/result/controller.py
> +        # Создать новый инстанс БД
Вот тут не поняла( ну у нас же где-то должно хранится сдал/не сдал? запись об этом. Тут имелось в виду что вот пользователь впервые попал на этот экзамен и еще у него нет никакого результата.

2020-07-22 12:24 UTC, LikaDevelop commented on app/templates/exam/status.html
> +        </tr>
Это вообще у меня бред полный... Это была попытка кое что реализовать о чем вчера не успела спросить надо ли оно/не надо ли. Идея тут была в том что бы Пользователю, во вкладке статус показать табличкой (как в Admin Dashboard) какие экзамены он прошел а какие завалил, в последствии у самого Админа будет так же видно только по нажатию на определенного юзера... Это идея такая, то что там полное не соответствие ей это да(

2020-07-22 12:25 UTC, LikaDevelop commented on app/result/views.py
> +    return render_template("exam/status.html", tabs=tabs, user=user, exam=exam)
Да, это все из той же моей "недо оперы"

2020-07-22 12:28 UTC, LikaDevelop commented on tests/test_exam_result.py
> +    # user = User.query.all()[0]
Я вчера не поборола, первые две строчки, оно мне в тесте выводило что мое значение, а именно 0, не входит в допустимые... indexerror: list index out of range. Вот такую ошибку выдавало.

2020-07-23 13:38 UTC, kipod commented on app/exam/views.py
> +    else:
если if block заканчивается return, то else: не нужен!!!

2020-07-23 13:38 UTC, kipod commented on app/result/controller.py
> +    # (возможно тут лучше будет использовать current_user)
нет не нужно тут использовать current_user.  Это не задача этой функции принимать решения апликативного уровня.

2020-07-23 13:38 UTC, kipod commented on app/result/controller.py
> +        # Создать новый инстанс БД
пиши что имела ввиду дословно!!! а то данный меня пугает 👍

2020-07-23 13:38 UTC, kipod commented on app/result/controller.py
> +        log(log.WARNING, "EXAM ALREADY NOT PASSED: %s", exam_id)
%s --> %d

2020-07-23 13:38 UTC, kipod commented on app/result/controller.py
> +    the_passed.save()
Правильный код этой функции:
```python
def go_pass_exam(exam_id: int, user_id: int):
    """Function mark exam as passed for the user

    Args:
        exam_id (int): exam ID
        user_id (int): user ID
    """
    result = Result.query.filter(
        Result.exam_id == exam_id, Result.user_id == user_id
    ).first()
    if not result:
        log(log.DEBUG, "Create new result: user_id:%d exam_id:%d", user_id, exam_id)
        result = Result(exam_id=exam_id, user_id=user_id)
    result.passed = True
    result.save()
```

2020-07-23 13:38 UTC, kipod commented on app/result/views.py
> +    exam_name = Exam.query.filter(Result.exam_id == Exam.id).all()
exam_name - название переменной
list of Exam instanses - тип хранимого значения
Лика, так нельзя называть переменные

2020-07-23 13:38 UTC, kipod commented on app/result/views.py
> +    user_id_results = Result.query.filter(Result.user_id == current_user.id).all()
плохое название переменной

2020-07-23 13:38 UTC, kipod commented on app/result/views.py
> +    exam_name = Exam.query.filter(Result.exam_id == Exam.id).all()
а ну и этот код не может работать в принципе
```
filter(Result.exam_id == Exam.id)
```
неправильная конструкция

2020-07-23 13:38 UTC, kipod commented on app/result/views.py
> +    user = current_user.username
ты не исправила!!

2020-07-23 13:38 UTC, kipod commented on app/result/views.py
> +    user_id_results = Result.query.filter(Result.user_id == current_user.id).all()
предлагаю results

2020-07-23 13:38 UTC, kipod commented on app/result/views.py
> +    exam_name = Exam.query.filter(Result.exam_id == Exam.id).all()
Удали эту строчку - exam_name в темплейте не используется вообще!!!

2020-07-23 14:57 UTC, kipod approved these changes

2020-07-23 14:57 UTC, kipod commented on app/result/models.py
> +
ладно - сам удалю потом 👎

2020-07-23 15:36 UTC, merged